version: '2.1'

networks:
  servers:

services:
  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: ./cmd/server
    networks:
      - servers
    ports:
      - "8080:8080"
    depends_on:
      - db

  server2:
    build: ./cmd/server
    networks:
      - servers
    ports:
      - "8081:8080"
    depends_on:
      - db

  server3:
    build: ./cmd/server
    networks:
      - servers
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    build: ./cmd/db
    networks:
      - servers
    ports:
      - "8083:8081"